version: '3.3'
services:
  covr:
    build: .
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.covr.tls'
      - 'traefik.http.routers.covr.tls.certresolver=letsencryptresolver'
      - 'traefik.http.services.covr.loadbalancer.server.port=3000'
      - 'traefik.http.routers.covr.rule=Host(`covr.ph1p.dev`)'
    environment:
      - PORT=3000
      - URL=https://covr.ph1p.dev
      - CLIENT_ID=
      - CLIENT_SECRET=
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
